### ISSUE TITLE
Subnominal Staging Error even when order is correct

### ISSUE THREAD

**Issue by Niyusha** [Qwarkk6/CLS#14]
Hello,
I managed to get one flight correctly with my rocket (3 stages, srbs) but after removing some liquid fuel tanks and replacing the clamps I get a subnominal launch error I cannot fix.

Feel like Im going a bit crazy since I checked the launch order and even ran through some incorrect launch configs to see if I could get past the error but I could not. Seems to be an issue inherent to the script.

Using Restock if that matters.

**Comment by Qwarkk6** [comment]
Hi Niyusha, thanks for bringing this to my attention.

Can you share the craft file please? And is restock the only mod you are using?

**Comment by Qwarkk6** [comment]
Issue closed due to lack of activity - CLS does allow for manual bypass of the subnominal staging error if necessary.
